stages:          # Liste des étapes du pipeline et leur ordre d'exécution
  - build
  - test

# Étape de compilation
build-job:
  stage: build
  script:
    - echo "Compiling the code..."
    - mvn clean install -DskipTests  # Compilation sans exécuter les tests
  artifacts:
    paths:
      - target/  # L'artefact généré sera dans le dossier 'target' (pour Maven)

# Étape de tests unitaires
unit-test-job:
  stage: test
  script:
    - echo "Running unit tests..."
    - mvn test  # Exécuter les tests unitaires
  artifacts:
    when: always  # Toujours garder les rapports de tests
    paths:
      - target/surefire-reports/  # Chemin des rapports de tests JUnit
  allow_failure: false  # Si les tests échouent, le pipeline échoue

# Étape de vérification de lint (optionnelle)
lint-test-job:
  stage: test
  script:
    - echo "Linting code..."
    - mvn checkstyle:check  # Vérification de la syntaxe avec Checkstyle
    - echo "Linting finished."
  allow_failure: true  # Si cette étape échoue, ça ne fait pas échouer le pipeline
