stages:
  - build
  - test
  - deploy

# Etape de Build
build:
  stage: build
  script:
    - mvn clean install
  artifacts:
    paths:
      - target/

# Etape de Test
test:
  stage: test
  script:
    - mvn test
  artifacts:
    when: always
    paths:
      - target/surefire-reports/
  allow_failure: false  

deploy:
  stage: deploy
  script:
    - echo "Déploiement réussi"
  only:
    - master 
  when: on_success  
